### ISSUE TITLE
Move Images to online storage

### ISSUE THREAD

**Issue by powderblock** [powderblock/Gabeifacation#10]
Move all images on website to online image storage. (Imgur, Dropbox, ImageShack, GitHub.)

**Comment by powderblock** [comment]
I think GitHub is the best bet for this.

**Comment by beefmaster** [comment]
i think this has been dealt with, considering you are referencing imgur for the images

**Comment by powderblock** [comment]
I left this open because in my mind I could do it better.  

I think it's safe to close.
